project/geekshop/adminapp/urls.py
import adminapp.views as adminapp
from django.urls import path
from adminapp.views import UsersListView, ProductCategoryCreateView, ProductCategoryUpdateView,ProductCategoryDeleteView, ProductDetailView

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.user_create, name='user_create'),
    path('users/read/', UsersListView.as_view(), name='users'),
    path('users/update/<int:pk>/', adminapp.user_update, name='user_update'),
    path('users/delete/<int:pk>/', adminapp.user_delete, name='user_delete'),

    path('categories/create/', ProductCategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', adminapp.categories, name='categories'),
    path('categories/update/<int:pk>/', ProductCategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', ProductCategoryDeleteView.as_view(), name='category_delete'),

    path('products/read/category/<int:pk>/', adminapp.products, name='products'),
    path('products/read/<int:pk>/', adminapp.product_read, name='product_read'),
    path('products/create/category/<int:pk>/', adminapp.product_create, name='product_create'),
    path('products/update/<int:pk>/', adminapp.product_update, name='product_update'),
    path('products/delete/<int:pk>/', adminapp.product_delete, name='product_delete'),
]

project/geekshop/authapp/urls.py
from django.urls import path
import authapp.views as authapp


app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    # path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),

    # path('login/', authapp.Login.as_view(), name='login'),
    path('logout/', authapp.Logout.as_view(), name='logout'),
    # path('register/', authapp.Register.as_view(), name='register'),
    # path('edit/', authapp.Edit.as_view(), name='edit'),

    # path('verify/<str:email>/<str:activate_key>/', authapp.Register.verify, name='verify')
]

project/geekshop/basketapp/urls.py
from django.urls import path
import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>)/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit')
]

project/geekshop/geekshop/urls.py
from django.contrib import admin
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.urls import re_path

app_name = 'mainapp'

urlpatterns = [
    # path('', mainapp.main, name='main'),
    # path('products/', include('mainapp.urls', namespace='products')),
    re_path(r'^$', mainapp.main, name='main'),
    re_path(r'^products/', include('mainapp.urls', namespace='products')),
    re_path(r'^order/', include('ordersapp.urls', namespace='order')),

    # re_path(r'^auth/', include('social_django.urls', namespace='social')),

    path('', include('social_django.urls', namespace='social')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('auth/', include('authapp.urls', namespace='auth')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/geekshop/mainapp/urls.py
from django.urls import path
import mainapp.views as mainapp
from django.urls import re_path

app_name = 'mainapp'
urlpatterns = [
    # path('', mainapp.products, name='index'),
    # path('category/<int:pk>/', mainapp.products, name='category'),
    # path('product/<int:pk>/', mainapp.product, name='product'),
    # path('category/<int:pk>/page/<int:page>/', mainapp.products, name='page'),

    re_path(r'^$', mainapp.products, name='index'),
    # re_path(r'^contact/', mainapp.contact, name='contact'),
    re_path(r'^category/(?P<pk>\d+)/$', mainapp.products, name='category'),
    re_path(r'^product/(?P<pk>\d+)/$', mainapp.product, name='product'),
    re_path(r'^category/(?P<pk>\d+)/page/(?P<page>\d+)/$', mainapp.products, name='page'),
]

project/geekshop/ordersapp/urls.py
import ordersapp.views as ordersapp
from django.urls import re_path

app_name = "ordersapp"

urlpatterns = [
    re_path(r'^$', ordersapp.OrderList.as_view(), name='orders_list'),
    re_path(r'^forming/complete/(?P<pk>\d+)/$', ordersapp.order_forming_complete, name='order_forming_complete'),
    re_path(r'^create/$', ordersapp.OrderItemsCreate.as_view(), name='order_create'),
    re_path(r'^read/(?P<pk>\d+)/$', ordersapp.OrderRead.as_view(), name='order_read'),
    re_path(r'^update/(?P<pk>\d+)/$', ordersapp.OrderItemsUpdate.as_view(), name='order_update'),
    re_path(r'^delete/(?P<pk>\d+)/$', ordersapp.OrderDelete.as_view(), name='order_delete'),
    re_path(r'^product/(?P<pk>\d+)/price/$', ordersapp.get_product_price)
]

project/geekshop/mainapp/models.py
from django.db import models
from django import forms
from django.forms import ModelForm


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

    @staticmethod
    def get_items():
        return Product.objects.filter(is_active=True).order_by('category', 'name')

project/geekshop/mainapp/views.py
from django.shortcuts import render
from .models import ProductCategory, Product
from django.shortcuts import get_object_or_404
import random
from basketapp.models import Basket
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.template import RequestContext


def main(request):
    title = 'главная'

    products = Product.objects.all()[:4]

    content = {'title': title, 'products': products}
    return render(request, 'mainapp/index.html', content)


# def contact(request):
#     title = 'контакты'
#     return render(request, 'mainapp/contact.html')


def products(request, pk=None, page=1):
    title = 'продукты'

    colors_1 = ['black', '#f4f4f4', 'grey']
    colors_2 = ['#fff', '#f4f4f4']

    links_menu = ProductCategory.objects.all()
    basket = get_basket(request.user)
    if pk is not None:
        if pk == 0:
            category = {
                'pk': 0,
                'name': 'все'
            }
            products = Product.objects.all().order_by('price')
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(category__pk=pk).order_by('price')
        paginator = Paginator(products, 6)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        content = {
            'color': colors_2,
            'title': title,
            'links_menu': links_menu,
            'category': category,
            'products': products_paginator,
            # 'basket': basket,
        }

        return render(request, 'mainapp/products_list.html', content)

    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)

    content = {
        'title': title,
        'links_menu': links_menu,
        'hot_product': hot_product,
        'same_products': same_products,
        # 'basket': basket,
        'product': Product.objects.filter(category__pk=pk).order_by('price'),
    }
    return render(request, 'mainapp/products.html', content)


def product(request, pk):
    title = 'продукты'

    content = {
        'title': title,
        'links_menu': ProductCategory.objects.all(),
        'product': get_object_or_404(Product, pk=pk),
        # 'basket': get_basket(request.user),
    }
    return render(request, 'mainapp/product.html', content)


def get_basket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    else:
        return []


def get_hot_product():
    products = Product.objects.all()
    return random.sample(list(products), 1)[0]


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category).exclude(pk=hot_product.pk)[:3]
    return same_products

project/geekshop/mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
  <meta charset="utf-8">
  <title>
    {% block title %}
    {{ title|capfirst }}
    {% endblock %}
  </title>

  {% block css %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% endblock %}

  {% block js %}
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

  {% endblock %}

</head>

<body>
<div class="container">
  {% block menu %}
  {% endblock %}

  {% block content %}
  {% endblock %}

</div>

</body>

</html>

project/geekshop/mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}
{% load static %}
<html>

<head>
  <meta charset="utf-8">
  <title>{% block title %}{% endblock %}</title>

  {% block css %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <style type="text/css">
    .inpt {
      background-image: url({% if user.image %}/media/{{ user.image }}
						{% else %} /media/users_avatars/default.png
						{% endif %});
      background-size: cover;
      background-position: center;
    }
  </style>
  {% endblock %}

  {% block js %}
  <script src="{% static 'js/product.js' %}"></script>
  {% endblock %}
</head>

<body>
  {% block menu %}
  <div class="slider">
    <div class="header clearfix log-hed">
      <a href="" class="logo"></a>
      <ul class="menu">
        {% include 'mainapp/includes/inc_menu.html' %}
        {% if not user.is_authenticated %}
        <li><a href="{% url 'auth:login' %}" class="log-name">Войти</a></li>
        {% endif %}

        {% if user.is_superuser %}
        <li><a href="{% url 'admin:users' %}" class="log-name">админка</a></li>
        {% endif %}
      </ul>

      {% if user.is_authenticated %}
      <div class="links-log-block">
        <div id="links" class="links-log">
          <div class="inpt" type="checkbox" value="Click" onmouseenter="viewDiv()" onmouseleave="hidDiv()">
            <div id="nav-link" class="nav-link">
              <a class="link-log link-1" id="link-1" href="{% url 'auth:edit' %}"><img class="link-img"
                  src="{% static 'img/6.png' %}" alt="#"></a>
              <a class="link-log link-2" id="link-2" href="{% url 'basket:view' %}"><img class="link-img"
                  src="{% static 'img/5.png' %}" alt="#"></a>
              <a class="link-log link-3" id="link-3" href="{% url 'order:orders_list' %}"><img class="link-img"
                  src="{% static 'img/7.png' %}" alt="#"></a>
            </div>
          </div>
        </div>
      </div>
      {% endif %}

      <a href="#" class="search"></a>
    </div>
    {% endblock %}

    {% block content %}
    <div class="text-slider">
      <h3 class="green">контакты</h3>
      <h3 class="big"> Связаться с нами</h3>
      <p>+723642746</p>
    </div>

  </div>
  {% endblock %}


</body>

</html>

project/geekshop/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}
<html>

<head>
  <meta charset="utf-8">
  <title>{% block title %}{% endblock %}</title>

  {% block css %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <style>
    .inpt {
      background-image: url({% if user.image %}/media/{{ user.image }}{% else %}/media/users_avatars/default.png{% endif %});
      background-size: cover;
      background-position: center;
    }
  </style>
  {% endblock %}

  {% block js %}
  <script src="{% static 'js/product.js' %}"></script>
  {% endblock %}
</head>

<body>
  {% block menu %}
  <div class="slider">
    <div class="header clearfix log-hed">
      <a href="" class="logo"></a>
        {% include 'mainapp/includes/inc_menu.html' %}
      <a href="#" class="search"></a>
    </div>
    {% endblock %}

    {% block content %}
    <div class="text-slider">
      <h3 class="green">тенденции</h3>
      <h3 class="big"> удобные стулья</h3>
      <p>Новый уровень комфорта. Отличные характеристики.</p>
      <a href="#" class="button-order">заказать</a>
    </div>
    <div class="navi">
      <a href="#"></a><a href="#"></a><a href="#"></a>
    </div>
  </div>
  {% endblock %}


</body>

</html>

project/geekshop/mainapp/templates/mainapp/product.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block css %}
<!--<link rel="stylesheet" href="{% static 'css/auth-admin.css' %}">-->
{% endblock %}

{% block content %}
<div class="product_read">

  <div class="summary">
    <img class="img-product" src="/media/{{ object.image|default:'products_images/default.jpg' }}" alt="{{ object.name }}">
    <div class="info-product">
    <p><b>Продукт: </b> {{ product.name|title }}</p>
    <p><b>Категория: </b> {{ product.category.name|title }}</p>
    <p><b>цена: </b>{{ product.price }} руб</p>
    <p><b>количество: </b>{{ product.quantity }}</p>
    <p><b>в каталоге: </b>{% if product.is_active %}да{% else %}нет{% endif %}</p>
    <div class="product_desc">
    <p><b>краткая информация: </b>{{ product.short_desc }}</p>
    <p><b>подробная информация: </b>{{ product.description }}</p>
    </div>
    </div>
  </div>
    <div  class="general-btm">
      <p>
      <button class="button">
        <a href="{% url 'admin:products' object.category.pk %}">
          <img src="/static/img/free-icon-long-arrow-pointing-to-the-right-25426.png" style="    transform: rotate(180deg);
 width: 20px;
    height: 20px; opacity: 0.5;
">
        </a>
      </button>
      </p>
      <div class="geeb-1">
        <div>
      <button  class="button">
        <a href="{% url 'admin:product_update' object.pk %}">
          редактировать
        </a>
      </button>
    </div>
    <p>
      <button class="button">
        <a href="{% url 'admin:product_delete' object.pk %}">
          удалить
        </a>
      </button>
    </p>
      </div>
  </div>
  </div>


{% endblock %}

project/geekshop/mainapp/templates/mainapp/products.html
<!DOCTYPE html>
{% extends 'mainapp/base.html' %}
{% load static %}
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Продукты{% endblock %}</title>

  {% block css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/mainapp-style.css' %}">
  <link rel="stylesheet" href="{% static 'css/style-all.css' %}">
  <style>
  html {
    background-color:{{ color.0 }};
  }
  .logo {
    opacity: 0;
  }
  </style>
  {% endblock %}

  {% block js %}
  {% endblock %}



</head>
<body>

{% block menu %}
<div class="container">
   <div class="slider">

    <div class="header clearfix log-hed">
      <a href="" class="logo"></a>
      <ul class="menu">
        {% include 'mainapp/includes/inc_menu.html' %}
        {% if not user.is_authenticated %}
        <li><a href="{% url 'auth:login' %}">Войти</a></li>
        {% endif %}

        {% if user.is_authenticated %}
        <li><a href="{% url 'basket:view' %}">корзина</a></li>

        {% if user.is_superuser %}
        <li><a href="{% url 'admin:users' %}">админка</a></li>
        {% endif %} </ul>

         <div class="cyrcle-li">
          <a class="cyc-1" href="{% url 'auth:edit' %}">
                        <img class="img-logg"
                 src="
						{% if not user.image %}
						/media/users_avatars/default.jpg
						{% endif %}
						{% if user.image %}
						/media/{{ user.image }}
						{% endif %}"
                 style="object-fit: cover; height: 50px;width: 50px; border-radius: 100%; ">
          </a>
        </div>
        {% endif %}


      <a href="#" class="search"></a>
    </div>
       <div class="details">
    <div class="links clearfix">
      {% include 'mainapp/includes/inc_categories_menu.html' %}
    </div>
    <div class="details-products">
      {% for product in products %}
      <div class="description">
         <img src="/media/{{ product.image }}" alt="#">
        <h3 class="big-bold">{{ product.name }}</h3>
        <br>
        <p class="price"> {{ product.price }} <span>руб</span></p>
        <a href="{% url 'products:product' product.pk %}" class="red-button">
          заказать
          <i class="fa fa-chevron-right" aria-hidden="true"></i>
        </a>
        <div class="description-text">
          {{ product.description }}
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
 {% endblock %}{% block content %}
  <div class="related">
    <div class="title clearfix">
      <h2>Похожие продукты</h2>
      <a class="explore" href="#">показать все <img src="/static/img/arrow.png" alt=""></a>
    </div>
    <div class="related-products clearfix">

      {% for product in products %}
      <div class="block">
        <a href="#">
          <img src="/media/{{ product.image }}" alt="{{ product.short_desc }}">
          <div class="text">
            <h1>?</h1>
            <h3>{{ product.category.name }}</h3>
            <h4>{{ product.name }}</h4>
            <p>{{ product.description }}</p>
          </div>
        </a>
      </div>
      {% endfor %}
    </div>
  </div>
   </div>
</div>
{% endblock %}

</body>
</html>

project/geekshop/mainapp/templates/mainapp/products_list.html
{% extends 'mainapp/base.html' %}
{% load static %}


{% block css %}
<link rel="stylesheet" href="{% static 'css/mainapp-style.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<style>
  .inpt {
    background-image: url({% if user.image %}/media/{{ user.image }}{% else %}/media/users_avatars/default.png{% endif %});
    background-size: cover;
    background-position: center;
  }
</style>
{% endblock %}

{% block js %}
<script src="{% static 'js/basket_scripts.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
<script src="{% static 'js/product.js' %}"></script>
{% endblock %}


<div class="container">
  {% block menu %}
  <div class="slider">
    <div class="header clearfix log-hed">
      <a href="" class="logo"></a>
        {% include 'mainapp/includes/inc_menu.html' %}
      <a href="#" class="search"></a>
    </div>
    {% endblock %}

    {% block content %}
    <div class="details">
      <div class="links ">
        {% include 'mainapp/includes/inc_categories_menu.html' %}
      </div>
      <div class="products_list">
        <div class="glav">
          <h2 class="categ-name">
            {% if category.name %}{{ category.name|title }}{% endif %}
            {% if not category.name %}Все{% endif %}</h2>
        </div>

        <div class="category-products">
          {% include 'mainapp/includes/card.html' %}
        </div>

        <div class="paginator">
          <a
                  href="{% if products.has_previous %}{% url 'products:page' category.pk products.previous_page_number %}{% else %}#{% endif %}">
            <img class="strelka-1" src="{% static 'img/strelka.png' %}"
                 style="{% if not products.has_previous %} opacity: 0; {% endif %} transform: rotate(180deg);">
          </a>
          <span class="current"><b>{{ products.number }}</b> / <b> {{ products.paginator.num_pages }}</b></span>
          <a
                  href="{% if products.has_next %}{% url 'products:page' category.pk products.next_page_number %}{% else %}#{% endif %}">
            <img class="strelka-2" src="{% static 'img/strelka.png' %}"
                 style="{% if not products.has_next %} opacity: 0; {% endif %}">
          </a>
        </div>
      </div>
    </div>

  </div>
  {% endblock %}

  {% block contact %}
  {% endblock %}