project/geekshop/adminapp/urls.py
import adminapp.views as adminapp
from django.urls import path
from adminapp.views import UsersListView, ProductCategoryCreateView, ProductCategoryUpdateView,ProductCategoryDeleteView, ProductDetailView

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.user_create, name='user_create'),
    path('users/read/', UsersListView.as_view(), name='users'),
    path('users/update/<int:pk>/', adminapp.user_update, name='user_update'),
    path('users/delete/<int:pk>/', adminapp.user_delete, name='user_delete'),

    path('categories/create/', ProductCategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', adminapp.categories, name='categories'),
    path('categories/update/<int:pk>/', ProductCategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', ProductCategoryDeleteView.as_view(), name='category_delete'),

    path('products/read/category/<int:pk>/', adminapp.products, name='products'),
    path('products/read/<int:pk>/', adminapp.product_read, name='product_read'),
    path('products/create/category/<int:pk>/', adminapp.product_create, name='product_create'),
    path('products/update/<int:pk>/', adminapp.product_update, name='product_update'),
    path('products/delete/<int:pk>/', adminapp.product_delete, name='product_delete'),
]

project/geekshop/authapp/urls.py
from django.urls import path
import authapp.views as authapp


app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    # path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),

    # path('login/', authapp.Login.as_view(), name='login'),
    path('logout/', authapp.Logout.as_view(), name='logout'),
    # path('register/', authapp.Register.as_view(), name='register'),
    # path('edit/', authapp.Edit.as_view(), name='edit'),

    # path('verify/<str:email>/<str:activate_key>/', authapp.Register.verify, name='verify')
]

project/geekshop/geekshop/urls.py
from django.contrib import admin
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.urls import re_path

app_name = 'mainapp'

urlpatterns = [
    # path('', mainapp.main, name='main'),
    # path('products/', include('mainapp.urls', namespace='products')),
    re_path(r'^$', mainapp.main, name='main'),
    re_path(r'^products/', include('mainapp.urls', namespace='products')),
    re_path(r'^order/', include('ordersapp.urls', namespace='order')),

    # re_path(r'^auth/', include('social_django.urls', namespace='social')),

    path('', include('social_django.urls', namespace='social')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('auth/', include('authapp.urls', namespace='auth')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/geekshop/adminapp/models.py
from django.db import models

# Create your models here.

project/geekshop/adminapp/forms.py
import hashlib
import random
from django.db import models
from django import forms
from authapp.models import User
from authapp.forms import UserEditForm
from django.contrib.auth.forms import UserCreationForm
from mainapp.models import ProductCategory
from mainapp.models import Product


class UserAdminRegisterForm(UserCreationForm):
     class Meta:
         model = User
         fields = '__all__'


class UserAdminEditForm(UserEditForm):

    class Meta:
        model = User
        fields = ('username', 'last_name', 'email', 'image', 'age')

    def __init__(self, *args, **kwargs):
        super(UserAdminEditForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['readonly'] = True
        self.fields['email'].widget.attrs['readonly'] = True

        for filed_name, filed in self.fields.items():
            filed.widget.attrs['class'] = 'form-control py-4'
        self.fields['image'].widget.attrs['class'] = 'custom-file-imput'


class ProductCategoryEditForm(forms.ModelForm):
    class Meta:
        model = ProductCategory
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class ProductEditForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

project/geekshop/adminapp/views.py
from authapp.models import User
from django.shortcuts import get_object_or_404, render
from mainapp.models import Product, ProductCategory
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse
from authapp.forms import UserRegisterForm
from adminapp.forms import UserAdminEditForm, ProductEditForm
from django.views.generic.list import ListView
from django.utils.decorators import method_decorator
from django.views.generic.edit import CreateView, UpdateView
from django.urls import reverse_lazy
from django.views.generic.edit import DeleteView
from django.views.generic.detail import DetailView
from adminapp.forms import ProductCategoryEditForm


class UsersListView(ListView):
    model = User
    template_name = 'adminapp/users.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class ProductCategoryCreateView(CreateView):
    model = ProductCategory
    template_name = 'adminapp/categories.html'
    success_url = reverse_lazy('admin:categories')
    fields = '__all__'


class ProductCategoryUpdateView(UpdateView):
    model = ProductCategory
    template_name = 'adminapp/category_update.html'
    success_url = reverse_lazy('admin:categories')
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'категории/редактирование'
        return context


class ProductCategoryDeleteView(DeleteView):
    model = ProductCategory
    template_name = 'adminapp/category_delete.html'
    success_url = reverse_lazy('admin:categories')


class ProductDetailView(DetailView):
    model = Product
    template_name = 'adminapp/product_read.html'


@user_passes_test(lambda u: u.is_superuser)
def users(request):
    title = 'админка/пользователи'
    users_list = User.objects.all().order_by('-is_active', '-is_superuser', '-is_staff', 'username')

    content = {
        'title': title,
        'objects': users_list
    }

    return render(request, 'adminapp/users.html', content)


def delete(self, request, *args, **kwargs):
    self.object = self.get_object()
    self.object.is_active = False
    self.object.save()
    return HttpResponseRedirect(self.get_success_url())


def user_create(request):
    title = 'пользователи/создание'
    if request.method == 'POST':
        user_form = UserRegisterForm(request.POST, request.FILES)

        if user_form.is_valid():
            user_form.save()
            return HttpResponseRedirect(reverse('admin:users'))
    else:
        user_form = UserRegisterForm()
    content = {'title': title, 'update_form': user_form}
    return render(request, 'adminapp/user_update.html', content)


def user_update(request, pk):
    title = 'пользователи/редактирование'

    edit_user = get_object_or_404(User, pk=pk)

    if request.method == 'POST':
        edit_form = UserAdminEditForm(request.POST, request.FILES, instance=edit_user)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('admin:user_update', args=[edit_user.pk]))
    else:

        edit_form = UserAdminEditForm(instance=edit_user)
    content = {'title': title, 'update_form': edit_form}
    return render(request, 'adminapp/user_update.html', content)


def user_delete(request, pk):
    title = 'пользователи/удаление'
    user = get_object_or_404(User, pk=pk)
    if request.method == 'POST':
        user.delete()
        # вместо удаления лучше сделаем неактивным
        # user.is_active = False
        # user.save()
        return HttpResponseRedirect(reverse('admin:users'))
    content = {'title': title, 'user_to_delete': user}
    return render(request, 'adminapp/user_delete.html', content)


def categories(request):
    title = 'админка/категории'
    categories_list = ProductCategory.objects.all()
    content = {
        'title': title,
        'objects': categories_list
    }
    return render(request, 'adminapp/categories.html', content)


def category_create(request):
    pass


def category_update(request, pk):
    title = 'категория/редактирование'
    edit_category = get_object_or_404(ProductCategory, pk=pk)
    if request.method == 'POST':
        edit_form = ProductEditForm(request.POST, request.FILES,
                                    instance=edit_category)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('admin:category_update',
                                                args=[edit_category.pk]))
    else:
        edit_form = ProductCategoryEditForm(instance=edit_category)
    content = {'title': title,
               'update_edit_category_form': edit_form,
               'category': edit_category,
               }
    return render(request, 'adminapp/category_update.html', content)


def category_delete(request, pk):
    title = 'продукт/удаление'
    category = get_object_or_404(ProductCategory, pk=pk)
    if request.method == 'POST':
        category.delete()
        # product.is_active = False
        # product.save()
        return HttpResponseRedirect(reverse('admin:categories',
                                            args=[category.pk]))
    content = {'title': title, 'category_to_delete': category}
    return render(request, 'adminapp/category_delete.html', content)


def products(request, pk):
    title = 'админка/продукт'
    category = get_object_or_404(ProductCategory, pk=pk)
    categories = ProductCategory.objects.all()
    products_list = Product.objects.filter(category__pk=pk).order_by('name')
    content = {
        'title': title,
        'category': category,
        'categories': categories,
        'objects': products_list,
    }

    return render(request, 'adminapp/products.html', content)


def product_create(request, pk):
    title = 'продукт/создание'
    category = get_object_or_404(ProductCategory, pk=pk)
    if request.method == 'POST':
        product_form = ProductEditForm(request.POST, request.FILES)
        if product_form.is_valid():
            product_form.save()
            return HttpResponseRedirect(reverse('admin:products', args=[pk]))
    else:
        product_form = ProductEditForm(initial={'category': category})

    content = {
        'title': title,
        'update_form': product_form,
        'category': category,
    }
    return render(request, 'adminapp/product_update.html', content)


def product_read(request, pk):
    title = 'продукт/подробнее'
    product = get_object_or_404(Product, pk=pk)
    content = {'title': title, 'object': get_object_or_404(Product, pk=pk), }
    return render(request, 'adminapp/product_read.html', content)


def product_update(request, pk):
    title = 'продукт/редактирование'
    edit_product = get_object_or_404(Product, pk=pk)
    if request.method == 'POST':
        edit_form = ProductEditForm(request.POST, request.FILES,
                                    instance=edit_product)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('admin:product_update',
                                                args=[edit_product.pk]))
    else:
        edit_form = ProductEditForm(instance=edit_product)
    content = {'title': title,
               'update_form': edit_form,
               'category': edit_product.category,
               }
    return render(request, 'adminapp/product_update.html', content)


def product_delete(request, pk):
    title = 'продукт/удаление'
    product = get_object_or_404(Product, pk=pk)
    if request.method == 'POST':
        product.delete()
        # product.is_active = False
        # product.save()
        return HttpResponseRedirect(reverse('admin:products',
                                            args=[product.category.pk]))
    content = {'title': title, 'product_to_delete': product}
    return render(request, 'adminapp/product_delete.html', content)

project/geekshop/adminapp/templates/adminapp/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">

  {% block css %}
  <link rel="stylesheet" href="{% static 'css/auth-admin.css' %}">
  {% endblock %}

  <title>GeekShop - Admin</title>

</head>
<body>
{% block menu %}

<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'main' %}">GeekShop</a>
</nav>
<div id="layoutSidenav">
  <div id="layoutSidenav_nav">
    <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
      <div class="sb-sidenav-menu">
        <div class="nav">
          <div class="sb-sidenav-menu-heading"></div>
          <a class="nav-link" href="{% url 'admin:users' %}">
            <div class="sb-nav-link-icon">
              <i class="fas fa-users"></i>
            </div>
            Пользователи
          </a>
          <a class="nav-link" href="{% url 'admin:categories' %}">
            <div class="sb-nav-link-icon">
              <i class="fas fa-shopping-basket"></i>
            </div>
            Категории
          </a>
        </div>
      </div>
      <div class="sb-sidenav-footer"></div>
    </nav>
  </div>
  <div id="layoutSidenav_content">
    <main>
      <div class="container-fluid">
        <h1 class="mt-4">Административная панель</h1>
      </div>
    </main>
    <div style="margin: 25px;">
      {% block content %}{% endblock %}
    </div>

    <footer class="py-4 bg-light mt-auto">

      <div class="container-fluid">

        <div class="d-flex align-items-center justify-content-between small">
          <div class="text-muted">Copyright &copy; GeekShop 2021</div>
        </div>
      </div>
    </footer>
  </div>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
          crossorigin="anonymous"></script>
  <script src="../js/auth-admin.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
  <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
  <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
  <script src="../js/datatable.js"></script>
  </ul>
  {% endblock %}
</body>

{% block js %}
{% endblock %}

</html>

project/geekshop/adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<div class="categories_list" style="margin: 25px;">
  <button  class="button">
    <a  href="{% url 'admin:category_create' %}">
      новая категория
    </a>
  </button>
  {% for object in objects %}
  <div class="category_record {% if not object.is_active %} not_active {% endif %}">
    <div class="brart">
      <div class="category_name">
        <b>
         {% if object.name %}
        {{ object.name|title }}
          {% endif %}
          {% if not object.name %}
          все
          {% endif %}
      </b>
      </div>
      <div class="category_desc">
        {{ object.description|title }}
      </div>
    </div>

    <div class="category_actions">
      <button class="button">
        <a href="{% url 'admin:products' object.pk %}">
          товары категории
        </a>
      </button>
      <button class="button">
        <a href="{% url 'admin:category_update' object.pk %}">
          редактировать
        </a>
      </button>
      <button class="button">
        <a href="{% url 'admin:category_delete' object.pk %}">
          удалить
        </a>
      </button>
    </div>

  </div>
  {% endfor%}
</div>
{% endblock %}

project/geekshop/adminapp/templates/adminapp/category_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% block content %}
<div class="user_delete">
  <div class="genereal-del">
    Уверены, что хотите удалить {{ user_to_delete.username }}
  {% if user_to_delete.first_name %}
  ({{ user_to_delete.first_name|title }}
  {% if user_to_delete.last_name %}
  {{ user_to_delete.last_name|title }}
  {% endif %})
  {% endif %}
  ?
  </div>
  <div class="bt-del-1">
    <form action="{% url 'admin:category_delete' category_to_delete.pk %}"
          method="post">
      {% csrf_token %}
      <input class="btn btn-danger" type="submit" value="удалить">
    </form>
    <button class="btn btn-success">
      <a class="btm-sucf" href="{% url 'admin:categories' %}">
        Отмена
      </a>
    </button>
  </div>

</div>
{% endblock %}

project/geekshop/adminapp/templates/adminapp/category_update.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/auth-admin.css' %}">
{% endblock %}

{% block content %}
<form class="form-horizontal" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ update_edit_category_form.as_p }}
  <input class="form-control" type="submit" value="сохранить">
</form>
<button class="btn btn-round form-control last">
  <a href="{% url 'admin:categories' %}">
    к списку категорий
  </a>
</button>
{% endblock %}

project/geekshop/adminapp/templates/adminapp/product_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<div class="user_delete">
Уверены, что хотите удалить {{ user_to_delete.username }}
{% if user_to_delete.first_name %}
({{ user_to_delete.first_name|title }}</b>
{% if user_to_delete.last_name %}
{{ user_to_delete.last_name|title }}
{% endif %})
{% endif %}
?
<form action="{% url 'admin:product_delete' product_to_delete.pk %}"
method="post">
{% csrf_token %}
<div class="btm-3">
  <input class="btn btn-danger" type="submit" value="удалить">
</form>
<button class="btn btn-success">
<a class="btn-success-a" href="{% url 'admin:products' product_to_delete.category.pk %}">
Отмена
</a>
</button>
</div>


</div>
{% endblock %}

project/geekshop/adminapp/templates/adminapp/product_read.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/auth-admin.css' %}">
{% endblock %}

{% block content %}
<div class="product_read">

  <div class="summary">
    <img class="img-product" src="/media/{{ object.image|default:'products_images/default.jpg' }}" alt="{{ object.name }}">
    <div class="info-product">
    <p><b>Продукт: </b> {{ object.name|title }}</p>
    <p><b>Категория: </b> {{ object.category.name|title }}</p>
    <p><b>цена: </b>{{ object.price }} руб</p>
    <p><b>количество: </b>{{ object.quantity }}</p>
    <p><b>в каталоге: </b>{% if object.is_active %}да{% else %}нет{% endif %}</p>
    <div class="product_desc">
    <p><b>краткая информация: </b>{{ object.short_desc }}</p>
    <p><b>подробная информация: </b>{{ object.description }}</p>
    </div>
    </div>
  </div>
    <div  class="general-btm">
      <p>
      <button class="button">
        <a href="{% url 'admin:products' object.category.pk %}">
          <img src="/static/img/free-icon-long-arrow-pointing-to-the-right-25426.png" style="    transform: rotate(180deg);
 width: 20px;
    height: 20px; opacity: 0.5;
">
        </a>
      </button>
      </p>
      <div class="geeb-1">
        <div>
      <button  class="button">
        <a href="{% url 'admin:product_update' object.pk %}">
          редактировать
        </a>
      </button>
    </div>
    <p>
      <button class="button">
        <a href="{% url 'admin:product_delete' object.pk %}">
          удалить
        </a>
      </button>
    </p>
      </div>
  </div>
  </div>


{% endblock %}

project/geekshop/adminapp/templates/adminapp/product_update.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/auth-admin.css' %}">
{% endblock %}

{% block content %}
<form class="form-horizontal" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ update_form.as_p }}
  <input class="form-control" type="submit" value="сохранить">
</form>
<button class="btn btn-round form-control last">
  <a href="{% url 'admin:categories' %}">
    к списку категорий
  </a>
</button>
{% endblock %}

project/geekshop/adminapp/templates/adminapp/products.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/auth-admin.css' %}">
{% endblock %}

{% block content %}
<button class="button new_product">
    <a href="{% url 'admin:product_create' category.pk %}">
      новый продукт
    </a>
  </button>
<div class="products_list">
  {% for object in objects %}
  <div class="product_record">
    <img class="img-products-1"
         src="/media/{{object.image|default:'products_images/default.jpg'}}"
         alt="{{ object.name }}">
    <div class="list-products">
      <div class="summary-info">
        <div class="inf-pr"><b>имя: </b>{{ object.name|title }}</div>
        <div class="inf-pr"><b>цена: </b>{{ object.price }} руб</div>
        <div class="inf-pr"><b>количество: </b>{{ object.quantity }}</div>
        <div class="inf-pr"><b>о продукте: </b>{{ object.short_desc|title }}</div>
      </div>
      <div class="product_actions">
        <button class="button">
          <a href="{% url 'admin:product_read' object.pk %}">
            подробнее
          </a>
        </button>
        <button class="button">
          <a href="{% url 'admin:product_update' object.pk %}">
            редактировать
          </a>
        </button>
        <button class="button">
          <a href="{% url 'admin:product_delete' object.pk %}">
            удалить
          </a>
        </button>
      </div>
    </div>


  </div>
  {% endfor%}
</div>
{% endblock %}

project/geekshop/adminapp/templates/adminapp/user_create.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block css %}
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/auth-admin.css' %}">
{% endblock %}

{% block menu %}
<div class="admin_menu">
  {% include 'adminapp/includes/inc_menu.html' %}
</div>
{% endblock %}

{% block content %}

<div id="layoutSidenav_content">
  <main>
    <div class="container-fluid">
      <h1 class="mt-4">Создание пользователя</h1>
      <form action="">
        <div class="form-row">
          <div class="col-lg-6">
            <div class="form-group">
              <label class="small mb-1" for="inputFirstName">Имя</label>
              <input class="form-control py-4" id="inputFirstName" type="text"/>
            </div>
          </div>
          <div class="col-lg-6">
            <div class="form-group">
              <label class="small mb-1" for="inputLastName">Фамилия</label>
              <input class="form-control py-4" id="inputLastName" type="text"/>
            </div>
          </div>
        </div>
        <div class="form-row mb-2">
          <div class="col-lg-12">
            <div class="custom-file">
              <input type="file" class="custom-file-input" id="userAvatar" size="50">
              <label class="custom-file-label" for="userAvatar">Выберите изображение</label>
            </div>
          </div>
        </div>
        <div class="form-row">
          <div class="col-lg-6">
            <label class="small mb-1" for="inputUsername">Имя пользователя</label>
            <input class="form-control py-4" id="inputUsername" type="text"
                   aria-describedby="usernameHelp"/>
          </div>
          <div class="col-lg-6">
            <label class="small mb-1" for="inputEmailAddress">Адрес электронной
              почты</label>
            <input class="form-control py-4" id="inputEmailAddress" type="email"
                   aria-describedby="emailHelp"/>
          </div>
        </div>
        <div class="form-row">
          <div class="col-lg-6">
            <label class="small mb-1" for="inputPassword1">Пароль</label>
            <input class="form-control py-4" id="inputPassword1" type="text"
                   aria-describedby="password1Help"/>
          </div>
          <div class="col-lg-6">
            <label class="small mb-1" for="inputPassword2">Повторите пароль</label>
            <input class="form-control py-4" id="inputPassword2" type="text"
                   aria-describedby="password2Help"/>
          </div>
        </div>
        <div class="form-row">
          <div class="col-lg-12" style="margin-top: 33px;">
            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
          </div>
        </div>
      </form>
    </div>
  </main>
  <footer class="py-4 bg-light mt-auto">
    <div class="container-fluid">
      <div class="d-flex align-items-center justify-content-between small">
        <div class="text-muted">Copyright &copy; GeekShop 2021</div>
      </div>
    </div>
  </footer>
</div>

{% endblock %}

{% block js %}
{% endblock %}

project/geekshop/adminapp/templates/adminapp/user_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% block content %}
<div class="user_delete">
  <div class="genereal-del">
    Уверены, что хотите удалить {{ user_to_delete.username }}
  {% if user_to_delete.first_name %}
  ({{ user_to_delete.first_name|title }}
  {% if user_to_delete.last_name %}
  {{ user_to_delete.last_name|title }}
  {% endif %})
  {% endif %}
  ?
  </div>
  <div class="bt-del-1">
    <form action="{% url 'admin:user_delete' user_to_delete.pk %}"
          method="post">
      {% csrf_token %}
      <input class="btn btn-danger" type="submit" value="удалить">
    </form>
    <button class="btn btn-success">
      <a class="btm-sucf" href="{% url 'admin:users' %}">
        Отмена
      </a>
    </button>
  </div>

</div>
{% endblock %}

project/geekshop/adminapp/templates/adminapp/user_update.html
{% extends 'authapp/base.html' %}
{% load static %}

  {% block css %}
  <link rel="stylesheet" href="{% static 'css/auth-admin.css' %}">
  {% endblock %}

{% block content %}
<form class="form-horizontal" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ update_form.as_p }}
  <input class="form-control" type="submit" value="сохранить">
</form>
<button class="bt-update">
  <a href="{% url 'admin:users' %}">
    к списку пользователей
  </a>
</button>
{% endblock %}

project/geekshop/adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/auth-admin.css' %}">
{% endblock %}

{% block content %}

<div class="users_list" style="">
  <button class="new_user button" style="margin: 25px;">
    <a href="{% url 'admin:user_create' %} ">новый пользователь</a>
  </button>
  <div style="margin: 25px; display: flex; flex-wrap: wrap; height: 100%;">
    {% for object in object_list %}
    <div
            class="user_record {% if not object.is_active %}not_active{% endif %}"
            style="">
      <div class="img-br">
        <img class="img-adm"
             src="/media/{{ object.image|default:'users_avatars/default.png' }}"
             alt="{{ object.username }}">
      </div>
      <div class="name-status">
        <div class="first-name-2"><strong>{{ object.username }}</strong></div>
        <div class="first-name-1">
          {% if object.last_name %}
          <b>{{ object.last_name|title }}</b>
          {% endif %}
        </div>
        <div class="stat-us">
          {% if object.is_superuser %}
          <div class="nike" style="color:green;">администратор</div>
          {% else %}
          <div class="nike">пользователь</div>
          {% endif %}
        </div>
      </div>

      <div class="inf-users">


        <div class="user_age">
          age: {{ object.age }} лет
        </div>
        <div class="user_email">
          email: {{ object.email }}
        </div>
        <div class="user_lastlogin">
          logged: {{ object.last_login }}
        </div>
      </div>

      <div class="user_role">
        <button class="button">
          <a href="{% url 'admin:user_update' object.pk %}">
            редактировать
          </a>
        </button>
        <button class="button del-btm-1">
          <a href="{% url 'admin:user_delete' object.pk %}">
            удалить
          </a>
        </button>
      </div>
    </div>
    {% endfor%}
  </div>
</div>
{% endblock %}