project/geekshop/adminapp/urls.py
import adminapp.views as adminapp
from django.urls import path
from adminapp.views import UsersListView, ProductCategoryCreateView, ProductCategoryUpdateView,ProductCategoryDeleteView, ProductDetailView

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.user_create, name='user_create'),
    path('users/read/', UsersListView.as_view(), name='users'),
    path('users/update/<int:pk>/', adminapp.user_update, name='user_update'),
    path('users/delete/<int:pk>/', adminapp.user_delete, name='user_delete'),

    path('categories/create/', ProductCategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', adminapp.categories, name='categories'),
    path('categories/update/<int:pk>/', ProductCategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', ProductCategoryDeleteView.as_view(), name='category_delete'),

    path('products/read/category/<int:pk>/', adminapp.products, name='products'),
    path('products/read/<int:pk>/', adminapp.product_read, name='product_read'),
    path('products/create/category/<int:pk>/', adminapp.product_create, name='product_create'),
    path('products/update/<int:pk>/', adminapp.product_update, name='product_update'),
    path('products/delete/<int:pk>/', adminapp.product_delete, name='product_delete'),
]

project/geekshop/authapp/urls.py
from django.urls import path
import authapp.views as authapp


app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    # path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),

    # path('login/', authapp.Login.as_view(), name='login'),
    path('logout/', authapp.Logout.as_view(), name='logout'),
    # path('register/', authapp.Register.as_view(), name='register'),
    # path('edit/', authapp.Edit.as_view(), name='edit'),

    # path('verify/<str:email>/<str:activate_key>/', authapp.Register.verify, name='verify')
]

project/geekshop/basketapp/urls.py
from django.urls import path
import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>)/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit')
]

project/geekshop/geekshop/urls.py
from django.contrib import admin
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.urls import re_path

app_name = 'mainapp'

urlpatterns = [
    # path('', mainapp.main, name='main'),
    # path('products/', include('mainapp.urls', namespace='products')),
    re_path(r'^$', mainapp.main, name='main'),
    re_path(r'^products/', include('mainapp.urls', namespace='products')),
    re_path(r'^order/', include('ordersapp.urls', namespace='order')),

    # re_path(r'^auth/', include('social_django.urls', namespace='social')),

    path('', include('social_django.urls', namespace='social')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('auth/', include('authapp.urls', namespace='auth')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/geekshop/mainapp/urls.py
from django.urls import path
import mainapp.views as mainapp
from django.urls import re_path

app_name = 'mainapp'
urlpatterns = [
    # path('', mainapp.products, name='index'),
    # path('category/<int:pk>/', mainapp.products, name='category'),
    # path('product/<int:pk>/', mainapp.product, name='product'),
    # path('category/<int:pk>/page/<int:page>/', mainapp.products, name='page'),

    re_path(r'^$', mainapp.products, name='index'),
    # re_path(r'^contact/', mainapp.contact, name='contact'),
    re_path(r'^category/(?P<pk>\d+)/$', mainapp.products, name='category'),
    re_path(r'^product/(?P<pk>\d+)/$', mainapp.product, name='product'),
    re_path(r'^category/(?P<pk>\d+)/page/(?P<page>\d+)/$', mainapp.products, name='page'),
]

project/geekshop/ordersapp/urls.py
import ordersapp.views as ordersapp
from django.urls import re_path

app_name = "ordersapp"

urlpatterns = [
    re_path(r'^$', ordersapp.OrderList.as_view(), name='orders_list'),
    re_path(r'^forming/complete/(?P<pk>\d+)/$', ordersapp.order_forming_complete, name='order_forming_complete'),
    re_path(r'^create/$', ordersapp.OrderItemsCreate.as_view(), name='order_create'),
    re_path(r'^read/(?P<pk>\d+)/$', ordersapp.OrderRead.as_view(), name='order_read'),
    re_path(r'^update/(?P<pk>\d+)/$', ordersapp.OrderItemsUpdate.as_view(), name='order_update'),
    re_path(r'^delete/(?P<pk>\d+)/$', ordersapp.OrderDelete.as_view(), name='order_delete'),
    re_path(r'^product/(?P<pk>\d+)/price/$', ordersapp.get_product_price)
]

project/geekshop/mainapp/models.py
from django.db import models
from django import forms
from django.forms import ModelForm


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

    @staticmethod
    def get_items():
        return Product.objects.filter(is_active=True).order_by('category', 'name')

project/geekshop/mainapp/views.py
from django.shortcuts import render
from .models import ProductCategory, Product
from django.shortcuts import get_object_or_404
import random
from basketapp.models import Basket
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.template import RequestContext


def main(request):
    title = 'главная'

    products = Product.objects.all()[:4]

    content = {'title': title, 'products': products}
    return render(request, 'mainapp/index.html', content)


# def contact(request):
#     title = 'контакты'
#     return render(request, 'mainapp/contact.html')


def products(request, pk=None, page=1):
    title = 'продукты'

    colors_1 = ['black', '#f4f4f4', 'grey']
    colors_2 = ['#fff', '#f4f4f4']

    links_menu = ProductCategory.objects.all()
    basket = get_basket(request.user)
    if pk is not None:
        if pk == 0:
            category = {
                'pk': 0,
                'name': 'все'
            }
            products = Product.objects.all().order_by('price')
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(category__pk=pk).order_by('price')
        paginator = Paginator(products, 6)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        content = {
            'color': colors_2,
            'title': title,
            'links_menu': links_menu,
            'category': category,
            'products': products_paginator,
            # 'basket': basket,
        }

        return render(request, 'mainapp/products_list.html', content)

    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)

    content = {
        'title': title,
        'links_menu': links_menu,
        'hot_product': hot_product,
        'same_products': same_products,
        # 'basket': basket,
        'product': Product.objects.filter(category__pk=pk).order_by('price'),
    }
    return render(request, 'mainapp/products.html', content)


def product(request, pk):
    title = 'продукты'

    content = {
        'title': title,
        'links_menu': ProductCategory.objects.all(),
        'product': get_object_or_404(Product, pk=pk),
        # 'basket': get_basket(request.user),
    }
    return render(request, 'mainapp/product.html', content)


def get_basket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    else:
        return []


def get_hot_product():
    products = Product.objects.all()
    return random.sample(list(products), 1)[0]


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category).exclude(pk=hot_product.pk)[:3]
    return same_products

project/geekshop/mainapp/templates/mainapp/includes/card.html
{% load static %}
<div class="card_add_basket">
  <div class="category-products">
    {% for product in products %}
    <div class="second_hide glav-block" id="second_hide_{{ product.pk }}" style="display:none">
      <div class="product-show">
        <p class="first_yelloy_" id="first_yelloy_{{ product.pk }}" style="display:none"
           onclick="first_yelloy({{ product.pk }})">
          <img class="img-close" src="{% static 'img/4.png' %}">
        </p>

        <div class="pr-3">
          <img class="img-pr-3" src="/media/{{ product.image }}" alt="{{ product.short_desc }}"><br>
          <div class="text-pr-2">
            <div class="pr-name-desk">
              <div class="name-pr-1"><b>{{ product.name }}</b></div>
              <div class="name-pr-7">{{ product.short_desc|truncatechars:50 }}</div>
              <div class="name-pr-2">{{ product.description|truncatechars:150 }}</div>
              <div class="name-pr-2"><b>категория: </b>{{ product.category.name }}</div>
              <div class="name-pr-6"><b>на складе: </b>{{ product.quantity }}</div>
            </div>
            <div class="btm-pr-1">
              <div class="name-pr-3">{{ product.price }} $</div>
              <div class="name-pr-4">
                {% if user.is_authenticated %}
                <button class="adm-bt bt-add bt-add-2" type="button" value="{{ product.pk }}"></button>
                {% endif %}
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
    <div class="block">
      <div class="bl-pr">
        <p id="first_{{ product.pk }}" onclick="first({{ product.pk }})">
          <img class="img-prd-1" src="/media/{{ product.image }}" alt="{{ product.short_desc }}">
        </p>
        <div class="text-pr-1">
          <h4 class="name-product-1">{{ product.name }}</h4>
          {% if not product.short_desc %}
          <p class="description-pr">описания нет</p>
          {% else %}
          <p class="description-pr">{{ product.short_desc|truncatechars:30 }}</p>
          {% endif %}
          <div class="down-pr">
            {% if user.is_authenticated %}
            {% if product.price == 0 %}
            <div class="cena">бесплатно</div>
            {% else %}
            <div class="cena">{{ product.price }} $</div>
            {% endif %}
            <button class="adm-bt bt-add bt-add-1" type="button" value="{{ product.pk }}"></button>
            {% else %}
            {% if product.price == 0 %}
            <div class="cena free-btm">бесплатно</div>
            {% else %}
            <div class="cena free-btm">{{ product.price }} $</div>
            {% endif %}

            {% endif %}
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

project/geekshop/mainapp/templates/mainapp/includes/inc_categories_menu.html
<ul class="links-menu">
  <li>
    <a href="{% url 'products:category' 0 %}"
       class="{% if request.resolver_match.kwargs.pk == '0' %}active{% endif %}">
      все
    </a>
  </li>
  {% for link in links_menu %}
  {% if link.pk != 0 %}
  <li>
    <a href="{% url 'products:category' link.pk %}"
       class="{% if request.resolver_match.kwargs.pk|add:'0' == link.pk %} active {% endif %}">
      {{ link.name }}
    </a>
  </li>
  {% endif %}
  {% endfor %}
</ul>

project/geekshop/mainapp/templates/mainapp/includes/inc_menu.html
{% load static %}

<ul class="menu">
  <li><a href="/" class="{% if title == 'главная' %}active{% endif %}">
    домой
  </a></li>
  <li><a href="{% url 'products:category' 0 %}" class="{% if title == 'продукты' %}active{% endif %}">
    продукты
  </a></li>

  {% if not user.is_authenticated %}
  <li><a href="{% url 'auth:login' %}" class="log-name">
    Войти
  </a></li>
  {% endif %}

  {% if user.is_superuser %}
  <li><a href="{% url 'admin:users' %}" class="log-name">
    админка
  </a></li>
  {% endif %}
</ul>
{% if user.is_authenticated %}
<div class="links-log-block">
  <div id="links" class="links-log">
    <div id="inpt" class="inpt" type="checkbox" value="Click" onmouseenter="viewDiv()" onmouseleave="hidDiv()">
      <div id="nav-link" class="nav-link">

        <a class="link-log link-1" id="link-1" href="{% url 'auth:edit' %}">
          <img class="link-img" src="{% static 'img/6.png' %}" alt="#">
        </a>

        <a class="link-log link-2" id="link-2" href="{% url 'basket:view' %}">
          <img class="link-img" src="{% static 'img/5.png' %}" alt="#">
        </a>

        <a class="link-log link-3" id="link-3" href="{% url 'order:orders_list' %}">
          <img class="link-img" src="{% static 'img/7.png' %}" alt="#">
        </a>

      </div>
    </div>
  </div>
</div>
{% endif %}