project/geekshop/authapp/urls.py
from django.urls import path
import authapp.views as authapp


app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    # path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),

    # path('login/', authapp.Login.as_view(), name='login'),
    path('logout/', authapp.Logout.as_view(), name='logout'),
    # path('register/', authapp.Register.as_view(), name='register'),
    # path('edit/', authapp.Edit.as_view(), name='edit'),

    # path('verify/<str:email>/<str:activate_key>/', authapp.Register.verify, name='verify')
]

project/geekshop/geekshop/urls.py
from django.contrib import admin
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.urls import re_path

app_name = 'mainapp'

urlpatterns = [
    # path('', mainapp.main, name='main'),
    # path('products/', include('mainapp.urls', namespace='products')),
    re_path(r'^$', mainapp.main, name='main'),
    re_path(r'^products/', include('mainapp.urls', namespace='products')),
    re_path(r'^order/', include('ordersapp.urls', namespace='order')),

    # re_path(r'^auth/', include('social_django.urls', namespace='social')),

    path('', include('social_django.urls', namespace='social')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('auth/', include('authapp.urls', namespace='auth')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/geekshop/ordersapp/urls.py
import ordersapp.views as ordersapp
from django.urls import re_path

app_name = "ordersapp"

urlpatterns = [
    re_path(r'^$', ordersapp.OrderList.as_view(), name='orders_list'),
    re_path(r'^forming/complete/(?P<pk>\d+)/$', ordersapp.order_forming_complete, name='order_forming_complete'),
    re_path(r'^create/$', ordersapp.OrderItemsCreate.as_view(), name='order_create'),
    re_path(r'^read/(?P<pk>\d+)/$', ordersapp.OrderRead.as_view(), name='order_read'),
    re_path(r'^update/(?P<pk>\d+)/$', ordersapp.OrderItemsUpdate.as_view(), name='order_update'),
    re_path(r'^delete/(?P<pk>\d+)/$', ordersapp.OrderDelete.as_view(), name='order_delete'),
    re_path(r'^product/(?P<pk>\d+)/price/$', ordersapp.get_product_price)
]

project/geekshop/ordersapp/models.py
from django.db import models
from django.conf import settings
from mainapp.models import Product


class Order(models.Model):
    FORMING = 'FM'
    SENT_TO_PROCEED = 'STP'
    PROCEEDED = 'PRD'
    PAID = 'PD'
    READY = 'RDY'
    CANCEL = 'CNC'

    ORDER_STATUS_CHOICES = (
        (FORMING, 'формируется'),
        (SENT_TO_PROCEED, 'отправлен в обработку'),
        (PAID, 'оплачен'),
        (PROCEEDED, 'обрабатывается'),
        (READY, 'готов к выдаче'),
        (CANCEL, 'отменен'),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created = models.DateTimeField(verbose_name='создан', auto_now_add=True)
    updated = models.DateTimeField(verbose_name='обновлен', auto_now=True)
    status = models.CharField(verbose_name='статус', max_length=3, choices=ORDER_STATUS_CHOICES, default=FORMING)
    is_active = models.BooleanField(verbose_name='активен', default=True)

    class Meta:
        ordering = ('-created',)
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'
    #
    # def __init__(self, *args, **kwargs):
    #     super().__init__(args, kwargs)
    #     self.orderitems = None

    def __str__(self):
        return 'Текущий заказ: {}'.format(self.id)

    def get_total_quantity(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity, items)))

    def get_product_type_quantity(self):
        items = self.orderitems.select_related()
        return len(items)

    def get_total_cost(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity * x.product.price, items)))

    def delete(self):
        for item in self.orderitems.select_related():
            item.product.quantity += item.quantity
            item.product.save()
        self.is_active = False
        self.save()


class OrderItemQuerySet(models.QuerySet):

    def delete(self, *args, **kwargs):
        for object in self:
            object.product.quantity += object.quantity
            object.product.save()
        super(OrderItemQuerySet, self).delete(*args, **kwargs)


class OrderItem(models.Model):
    objects = OrderItemQuerySet.as_manager()
    order = models.ForeignKey(Order, related_name="orderitems",  on_delete=models.CASCADE)
    product = models.ForeignKey(Product, verbose_name='продукт', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='количество', default=0)

    def get_product_cost(self):
        return self.product.price * self.quantity

project/geekshop/ordersapp/forms.py
from django import forms
from ordersapp.models import Order, OrderItem
from mainapp.models import Product


class OrderForm(forms.ModelForm):

    class Meta:
        model = Order
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            self.fields['product'].queryset = Product.get_items()


class OrderItemForm(forms.ModelForm):
    price = forms.CharField(label='цена', required=False)

    class Meta:
        model = OrderItem
        exclude = ()

    def __init__(self, *args, **kwargs):
        super(OrderItemForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

project/geekshop/ordersapp/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.db import transaction
from django.forms import inlineformset_factory
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from basketapp.models import Basket
from ordersapp.models import Order, OrderItem
from ordersapp.forms import OrderItemForm
from django.dispatch import receiver
from django.db.models.signals import pre_save, pre_delete
from django.http import JsonResponse
from mainapp.models import Product


def product_quantity_update_save(sender, update_fields, instance, **kwargs):
    # if instance.pk:
    #     item = instance.get_item(int(instance.pk))
    #     instance.product.quantity -= instance.quantity - item
    # else:
    #     instance.product.quantity -= instance.quantity
    # instance.product.save()

    if update_fields is 'quantity' or 'product':
        if instance.pk:
            instance.product.quantity -= instance.quantity - sender.get_item(instance.pk).quantity
    else:
        instance.product.quantity -= instance.quantity
    instance.product.save()


def product_quantity_update_delete(sender, instance, **kwargs):
    instance.product.quantity += instance.quantity
    instance.product.save()


class OrderList(ListView):
    model = Order

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)


class OrderItemsCreate(CreateView):
    model = Order
    fields = []
    success_url = reverse_lazy('ordersapp:orders_list')

    def get_context_data(self, **kwargs):
        data = super(OrderItemsCreate, self).get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)
        if self.request.POST:
            formset = OrderFormSet(self.request.POST)
        else:
            basket_items = Basket.objects.filter(user=self.request.user)
            if len(basket_items):
                OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=len(basket_items))
                formset = OrderFormSet()
                for num, form in enumerate(formset.forms):
                    form.initial['product'] = basket_items[num].product
                    form.initial['quantity'] = basket_items[num].quantity
                    form.initial['price'] = basket_items[num].product.price
                    basket_items[num].delete()
                # basket_items.delete()
            else:
                formset = OrderFormSet()

        data['orderitems'] = formset
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            form.instance.user = self.request.user
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()
            # удаляем пустой заказ
        if self.object.get_total_cost() == 0:
            self.object.delete()

        return super(OrderItemsCreate, self).form_valid(form)


class OrderItemsUpdate(UpdateView):
    model = Order
    fields = []
    success_url = reverse_lazy('ordersapp:orders_list')

    def get_context_data(self, **kwargs):
        data = super(OrderItemsUpdate, self).get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)
        if self.request.POST:
            data['orderitems'] = OrderFormSet(self.request.POST, instance=self.object)
        else:
            # data['orderitems'] = OrderFormSet(instance=self.object)
            formset = OrderFormSet(instance=self.object)
            for form in formset.forms:
                if form.instance.pk:
                    form.initial['price'] = form.instance.product.price
            data['orderitems'] = formset
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']
        with transaction.atomic():
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()

        # удаляем пустой заказ
        if self.object.get_total_cost() == 0:
            self.object.delete()

        return super(OrderItemsUpdate, self).form_valid(form)


class OrderDelete(DeleteView):
    model = Order
    success_url = reverse_lazy('ordersapp:orders_list')
    title = 'Удаление закахов'


class OrderRead(DetailView):
    model = Order

    def get_context_data(self, **kwargs):
        context = super(OrderRead, self).get_context_data(**kwargs)
        context['title'] = 'заказ/просмотр'
        return context


def order_forming_complete(request, pk):
    order = get_object_or_404(Order, pk=pk)
    order.status = Order.SENT_TO_PROCEED
    order.save()
    return HttpResponseRedirect(reverse('ordersapp:orders_list'))


def get_product_price(request, pk):
        if request.is_ajax():
            product = Product.objects.filter(pk=int(pk)).first()
            if product:
                return JsonResponse({'price': product.price})
            else:
                return JsonResponse({'price': 0})

project/geekshop/ordersapp/templates/ordersapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <meta charset="utf-8">
  <title>
    {% block title %}
    {{ title|title }}
    {% endblock %}
  </title>

  {% block css %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%}">
  <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/order-style.css' %}">
  {% endblock %}

  {% block js %}
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
  {% endblock %}

</head>
<body>
<div class="order_container">
  {% block content %}
  {% endblock %}
</div>
</body>
</html>

project/geekshop/ordersapp/templates/ordersapp/order_confirm_delete.html
{% extends 'ordersapp/base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/order-style.css' %}">
{% endblock %}

{% block content %}
<div class="category_delete">
  {% include 'ordersapp/includes/inc_order_summary.html' %}
  <form class="btn-del-ord" action="{% url 'ordersapp:order_delete' object.pk %}" method="post">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="удалить">
    <button class="btn btn-success">
      <a href="{% url 'ordersapp:orders_list' %}">отмена</a>
    </button>
  </form>
</div>
{% endblock %}

project/geekshop/ordersapp/templates/ordersapp/order_detail.html
{% extends "ordersapp/base.html" %}
{% load static %}
{% load my_tags %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/order-style.css' %}">
{% endblock %}

{% block content %}
<div class="general-ord-2">

  {% include 'ordersapp/includes/inc_order_summary.html' %}
  <div class="basket_list">
    {% for item in object.orderitems.select_related %}
    <div class="basket_record">
      <img src="{{ item.product.image|media_folder_products }}"
           alt="{{ item.product.short_desc }}"
           class="img-pr-ord">
      <div class="info-pr-ord-1">
              <span class="category_name"><b>Категория: </b>
{{ item.product.category.name }}
</span>
        <span class="product_name"><b>Имя: </b>{{ item.product.name }}</span>
        </div>
        <div class="info-pr-ord-2">

        <span class="product_price">
{{ item.product.price }}&nbspруб
</span>
        <span class="product_quantitiy">
x {{ item.quantity }} шт.
</span>
        <span class="product_cost">
= {{ item.get_product_cost }}&nbspруб
</span>
        </div>



    </div>
    {% endfor %}
  </div>
  <div class="btm-form-ord">{% include 'ordersapp/includes/inc_order_actions.html' %}</div>

</div>
{% endblock %}

project/geekshop/ordersapp/templates/ordersapp/order_form.html
{% extends "ordersapp/base.html" %}
{% load static %}
{% block content %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/order-style.css' %}">
{% endblock %}

<div class="general-cont">
  {% include 'ordersapp/includes/inc_order_summary.html' %}
  <div class="order_form-1">
    <form class="info-new-ord" action="" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <table class="table">
        {{ orderitems.management_form }}
        {% for form in orderitems.forms %}
        {% if forloop.first %}
        <thead>
        <tr>
          {% for field in form.visible_fields %}
          <th class="{% cycle 'td11' 'td22' 'td33' %} order formset_td">
            {{ field.label|capfirst }}
          </th>
          {% endfor %}
        </tr>
        </thead>
        {% endif %}
        <tr class="formset_row">
          {% for field in form.visible_fields %}
          <td class="{% cycle 'td11' 'td22' 'td33' %} order formset_td">
            {% if forloop.first %}
            {% for hidden in form.hidden_fields %}
            {{ hidden }}
            {% endfor %}
            {% endif %}
            {{ field.errors.as_ul }}
            {% if field.name != 'price' %}
            {{ field }}
            {% else %}
            {% if field.value %}
            <span class="orderitems-{{forloop.parentloop.counter0}}-price">{{ field.value }}</span> руб
            {% endif %}
            {% endif %}
          </td>
          {% endfor %}
        </tr>
        {% endfor %}
      </table>
      <div class="btm-new-ord">
        <script>
            $('.formset_row').formset({
              addText: 'добавить продукт',
              deleteText: 'удалить',
              prefix: 'orderitems',
              removed: deleteOrderItem
            });
        </script>
        <button type="submit" value="сохранить" class="btn btn-default btn-round form-control last">
          сохранить
        </button>
        {% include 'ordersapp/includes/inc_order_actions.html' %}
      </div>

    </form>
  </div>
  {% endblock %}
</div>

project/geekshop/ordersapp/templates/ordersapp/order_list.html
{% extends 'ordersapp/base.html' %}
{% load static %}

{% block css %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/order-style.css' %}">
{% endblock %}

{% block content %}

<div class="btm-general">
  <div class="h2 text-center head">
  {% if user.username %}
  <b>{{ user.username|title}}</b>
  {% elif user.first_name %}
  {{ user.first_name|title}}
  {% else %}
  Пользователь
  {% endif %}
</div>

</div>
{% if object_list|length != 0 %}
<table class="table orders_list">
  <thead>
  <tr class="tr-1">
    <th class="id-ord">ID</th>
    <th>Создан</th>
    <th>Обновлен</th>
    <th>Статус</th>
    <th class="instrumebt">Инструменты</th>
  </tr>
  </thead>
  <tbody>
  {% for item in object_list %}
  {% if item.is_active %}
  <tr class="tr-2">
    <td class="td1">{{ item.pk }}</td>
    <td class="date">{{ item.created|date:"Y-m-d H:i:s" }}</td>
    <td class="updated">{{ item.updated|date:"Y-m-d H:i:s" }}</td>
    <td class="status">{{ item.get_status_display }}</td>
    <td class="tr-3">
    <button class="btn-ord">
      <a href="{% url 'ordersapp:order_read' item.pk %}">
        посмотреть
      </a>
    </button>
    {% if item.status == 'FM' %}
    <button class="btn-ord">

      <a href="{% url 'ordersapp:order_update' item.pk %}">
        редактировать
      </a>

    </button >
      {% endif %}
    {% if item.status == 'FM' %}
    <button class="btn-ord">

      <a href="{% url 'ordersapp:order_delete' item.pk %}">
        удалить
      </a>

    </button>
      {% endif %}
    </td>
  </tr>

  {% endif %}
  {% endfor %}

  </tbody>
</table>

<div class="btm-form-ord">
  <button class="btn btn-default btn-round">
  <a href="{% url 'main' %}">
    на главную
  </a>
</button>
  <button class="btn btn-default btn-round">
  <a href="{% url 'ordersapp:order_create' %}">
    новый
  </a>
</button>
</div>

{% else %}
<div class="text-1">
  заказов нет
</div>
<div class="btm-form-ord">

  <button class="btn btn-default btn-round">
  <a href="{% url 'main' %}">
    на главную
  </a>
</button>
  <button class="btn btn-default btn-round">
  <a href="{% url 'ordersapp:order_create' %}">
    новый
  </a>
</button>
</div>

{% endif %}

{% endblock %}